# Generated by Django 5.2.7 on 2025-11-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_board_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
